version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout

      - restore_cache:
        keys:
          - cache-{{checksum "requirements/requirements.txt"}-{checksum "requirements/requirements-dev.txt"}}

      - run:
          name: Install requirements
          command:
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
      - save_cache:
        key: cache-{{checksum "requirements/requirements.txt"}-{checksum "requirements/requirements-dev.txt"}}
        paths:
          - ~/.local

    steps:
      - run:
          name: Run linting
          when: always